# Wire up travis
language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
  - pypy3

#install: python setup.py develop  # install doesn't seem to be needed for testing

script: python setup.py test -q
